generate_response_task:
  description: >
    Intent of the question is {input}, Generate a proper answer including historical importance and key features.
  expected_output: >
    A natural language sort summary not more then 3 to 4 lines.

